### ISSUE TITLE
Using a Topology Symbol as a Qualifier Causes a Crash

### ISSUE THREAD

**Issue by LeStarch** [fprime-community/fpp#350]
Adding the following line to the F´ `Ref` topology causes the below stack trace.  It should instead say "topology Ref.MyTopology does not exist"

```
   topology Ref {
+    import Ref.MyTopology
```

**Comment by LeStarch** [comment]
Here is the error text:
```
Exception in thread "main" java.util.NoSuchElementException: key not found: Topology((List(),AstNode(DefTopology(Ref,List(TopologyMember((List(),SpecTopImport(AstNode(SpecTopImport(AstNode(Qualified(AstNode(Unqualified(Ref),1558),AstNode(MyTopology,1559)),1560)),1561)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(health),1563)),1564)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(SG1),1566)),1567)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(SG2),1569)),1570)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(SG3),1572)),1573)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(SG4),1575)),1576)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(SG5),1578)),1579)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(blockDrv),1581)),1582)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(tlmSend),1584)),1585)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(cmdDisp),1587)),1588)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(cmdSeq),1590)),1591)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(comm),1593)),1594)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(downlink),1596)),1597)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(eventLogger),1599)),1600)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(fatalAdapter),1602)),1603)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(fatalHandler),1605)),1606)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(fileDownlink),1608)),1609)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(fileManager),1611)),1612)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(fileUplink),1614)),1615)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(fileUplinkBufferManager),1617)),1618)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(posixTime),1620)),1621)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(pingRcvr),1623)),1624)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(prmDb),1626)),1627)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(rateGroup1Comp),1629)),1630)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(rateGroup2Comp),1632)),1633)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(rateGroup3Comp),1635)),1636)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(rateGroupDriverComp),1638)),1639)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(recvBuffComp),1641)),1642)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(sendBuffComp),1644)),1645)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(staticMemory),1647)),1648)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(textLogger),1650)),1651)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(typeDemo),1653)),1654)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(uplink),1656)),1657)),List())), TopologyMember((List(),SpecCompInstance(AstNode(SpecCompInstance(public,AstNode(Unqualified(systemResources),1659)),1660)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Pattern(command,AstNode(Unqualified(cmdDisp),1662),List()),1663)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Pattern(event,AstNode(Unqualified(eventLogger),1665),List()),1666)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Pattern(param,AstNode(Unqualified(prmDb),1668),List()),1669)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Pattern(telemetry,AstNode(Unqualified(tlmSend),1671),List()),1672)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Pattern(text event,AstNode(Unqualified(textLogger),1674),List()),1675)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Pattern(time,AstNode(Unqualified(posixTime),1677),List()),1678)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Pattern(health,AstNode(Unqualified(health),1680),List()),1681)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Direct(Downlink,List(Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(tlmSend),1684),AstNode(PktSend,1683)),1685),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(downlink),1688),AstNode(comIn,1687)),1689),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(eventLogger),1692),AstNode(PktSend,1691)),1693),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(downlink),1696),AstNode(comIn,1695)),1697),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(fileDownlink),1700),AstNode(bufferSendOut,1699)),1701),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(downlink),1704),AstNode(bufferIn,1703)),1705),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(downlink),1708),AstNode(framedAllocate,1707)),1709),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(staticMemory),1712),AstNode(bufferAllocate,1711)),1713),Some(AstNode(ExprDot(AstNode(ExprIdent(Ports_StaticMemory),1714),AstNode(downlink,1715)),1716))), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(downlink),1719),AstNode(framedOut,1718)),1720),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(comm),1723),AstNode(send,1722)),1724),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(downlink),1727),AstNode(bufferDeallocate,1726)),1728),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(fileDownlink),1731),AstNode(bufferReturn,1730)),1732),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(comm),1735),AstNode(deallocate,1734)),1736),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(staticMemory),1739),AstNode(bufferDeallocate,1738)),1740),Some(AstNode(ExprDot(AstNode(ExprIdent(Ports_StaticMemory),1741),AstNode(downlink,1742)),1743))))),1744)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Direct(FaultProtection,List(Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(eventLogger),1747),AstNode(FatalAnnounce,1746)),1748),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(fatalHandler),1751),AstNode(FatalReceive,1750)),1752),None))),1753)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Direct(RateGroups,List(Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(blockDrv),1756),AstNode(CycleOut,1755)),1757),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroupDriverComp),1760),AstNode(CycleIn,1759)),1761),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroupDriverComp),1764),AstNode(CycleOut,1763)),1765),Some(AstNode(ExprDot(AstNode(ExprIdent(Ports_RateGroups),1766),AstNode(rateGroup1,1767)),1768)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup1Comp),1771),AstNode(CycleIn,1770)),1772),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup1Comp),1775),AstNode(RateGroupMemberOut,1774)),1776),Some(AstNode(ExprLiteralInt(0),1777)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(SG1),1780),AstNode(schedIn,1779)),1781),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup1Comp),1784),AstNode(RateGroupMemberOut,1783)),1785),Some(AstNode(ExprLiteralInt(1),1786)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(SG2),1789),AstNode(schedIn,1788)),1790),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup1Comp),1793),AstNode(RateGroupMemberOut,1792)),1794),Some(AstNode(ExprLiteralInt(2),1795)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(tlmSend),1798),AstNode(Run,1797)),1799),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup1Comp),1802),AstNode(RateGroupMemberOut,1801)),1803),Some(AstNode(ExprLiteralInt(3),1804)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(fileDownlink),1807),AstNode(Run,1806)),1808),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup1Comp),1811),AstNode(RateGroupMemberOut,1810)),1812),Some(AstNode(ExprLiteralInt(4),1813)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(systemResources),1816),AstNode(run,1815)),1817),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroupDriverComp),1820),AstNode(CycleOut,1819)),1821),Some(AstNode(ExprDot(AstNode(ExprIdent(Ports_RateGroups),1822),AstNode(rateGroup2,1823)),1824)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup2Comp),1827),AstNode(CycleIn,1826)),1828),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup2Comp),1831),AstNode(RateGroupMemberOut,1830)),1832),Some(AstNode(ExprLiteralInt(0),1833)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(cmdSeq),1836),AstNode(schedIn,1835)),1837),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup2Comp),1840),AstNode(RateGroupMemberOut,1839)),1841),Some(AstNode(ExprLiteralInt(1),1842)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(sendBuffComp),1845),AstNode(SchedIn,1844)),1846),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup2Comp),1849),AstNode(RateGroupMemberOut,1848)),1850),Some(AstNode(ExprLiteralInt(2),1851)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(SG3),1854),AstNode(schedIn,1853)),1855),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup2Comp),1858),AstNode(RateGroupMemberOut,1857)),1859),Some(AstNode(ExprLiteralInt(3),1860)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(SG4),1863),AstNode(schedIn,1862)),1864),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroupDriverComp),1867),AstNode(CycleOut,1866)),1868),Some(AstNode(ExprDot(AstNode(ExprIdent(Ports_RateGroups),1869),AstNode(rateGroup3,1870)),1871)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup3Comp),1874),AstNode(CycleIn,1873)),1875),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup3Comp),1878),AstNode(RateGroupMemberOut,1877)),1879),Some(AstNode(ExprLiteralInt(0),1880)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(health),1883),AstNode(Run,1882)),1884),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup3Comp),1887),AstNode(RateGroupMemberOut,1886)),1888),Some(AstNode(ExprLiteralInt(1),1889)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(SG5),1892),AstNode(schedIn,1891)),1893),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup3Comp),1896),AstNode(RateGroupMemberOut,1895)),1897),Some(AstNode(ExprLiteralInt(2),1898)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(blockDrv),1901),AstNode(Sched,1900)),1902),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(rateGroup3Comp),1905),AstNode(RateGroupMemberOut,1904)),1906),Some(AstNode(ExprLiteralInt(3),1907)),AstNode(PortInstanceIdentifier(AstNode(Unqualified(fileUplinkBufferManager),1910),AstNode(schedIn,1909)),1911),None))),1912)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Direct(Ref,List(Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(sendBuffComp),1915),AstNode(Data,1914)),1916),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(blockDrv),1919),AstNode(BufferIn,1918)),1920),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(blockDrv),1923),AstNode(BufferOut,1922)),1924),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(recvBuffComp),1927),AstNode(Data,1926)),1928),None))),1929)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Direct(Sequencer,List(Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(cmdSeq),1932),AstNode(comCmdOut,1931)),1933),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(cmdDisp),1936),AstNode(seqCmdBuff,1935)),1937),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(cmdDisp),1940),AstNode(seqCmdStatus,1939)),1941),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(cmdSeq),1944),AstNode(cmdResponseIn,1943)),1945),None))),1946)),List())), TopologyMember((List(),SpecConnectionGraph(AstNode(Direct(Uplink,List(Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(comm),2107),AstNode(allocate,2106)),2108),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(staticMemory),2111),AstNode(bufferAllocate,2110)),2112),Some(AstNode(ExprDot(AstNode(ExprIdent(Ports_StaticMemory),2113),AstNode(uplink,2114)),2115))), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(comm),2118),AstNode(recv,2117)),2119),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(uplink),2122),AstNode(framedIn,2121)),2123),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(uplink),2126),AstNode(framedDeallocate,2125)),2127),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(staticMemory),2130),AstNode(bufferDeallocate,2129)),2131),Some(AstNode(ExprDot(AstNode(ExprIdent(Ports_StaticMemory),2132),AstNode(uplink,2133)),2134))), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(uplink),2137),AstNode(comOut,2136)),2138),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(cmdDisp),2141),AstNode(seqCmdBuff,2140)),2142),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(cmdDisp),2145),AstNode(seqCmdStatus,2144)),2146),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(uplink),2149),AstNode(cmdResponseIn,2148)),2150),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(uplink),2153),AstNode(bufferAllocate,2152)),2154),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(fileUplinkBufferManager),2157),AstNode(bufferGetCallee,2156)),2158),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(uplink),2161),AstNode(bufferOut,2160)),2162),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(fileUplink),2165),AstNode(bufferSendIn,2164)),2166),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(uplink),2169),AstNode(bufferDeallocate,2168)),2170),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(fileUplinkBufferManager),2173),AstNode(bufferSendIn,2172)),2174),None), Connection(AstNode(PortInstanceIdentifier(AstNode(Unqualified(fileUplink),2177),AstNode(bufferSendOut,2176)),2178),None,AstNode(PortInstanceIdentifier(AstNode(Unqualified(fileUplinkBufferManager),2181),AstNode(bufferSendIn,2180)),2182),None))),2183)),List())))),2184),List()))
	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:631)
	at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
	at fpp.compiler.analysis.CheckUses$.visitQualified$1$$anonfun$1(CheckUses.scala:156)
	at scala.util.Either.flatMap(Either.scala:352)
	at fpp.compiler.analysis.CheckUses$.visitQualified$1(CheckUses.scala:163)
	at fpp.compiler.analysis.CheckUses$.visitQualIdentNode(CheckUses.scala:168)
	at fpp.compiler.analysis.CheckUses$.topologyUse(CheckUses.scala:113)
	at fpp.compiler.analysis.UseAnalyzer.specTopImportAnnotatedNode$$anonfun$1(UseAnalyzer.scala:121)
	at fpp.compiler.analysis.UseAnalyzer.qualIdentNode(UseAnalyzer.scala:136)
	at fpp.compiler.analysis.UseAnalyzer.specTopImportAnnotatedNode(UseAnalyzer.scala:121)
	at fpp.compiler.analysis.UseAnalyzer.specTopImportAnnotatedNode$(UseAnalyzer.scala:7)
	at fpp.compiler.analysis.CheckUses$.specTopImportAnnotatedNode(CheckUses.scala:7)
	at fpp.compiler.analysis.CheckUses$.specTopImportAnnotatedNode(CheckUses.scala:7)
	at fpp.compiler.ast.AstVisitor.matchTopologyMember(AstVisitor.scala:150)
	at fpp.compiler.ast.AstVisitor.matchTopologyMember$(AstVisitor.scala:4)
	at fpp.compiler.analysis.CheckUses$.matchTopologyMember(CheckUses.scala:7)
	at fpp.compiler.analysis.TopologyAnalyzer.defTopologyAnnotatedNode$$anonfun$1(TopologyAnalyzer.scala:16)
	at fpp.compiler.util.Result$.foldLeft(Result.scala:16)
	at fpp.compiler.ast.AstStateVisitor.visitList(AstStateVisitor.scala:25)
	at fpp.compiler.ast.AstStateVisitor.visitList$(AstStateVisitor.scala:6)
	at fpp.compiler.analysis.CheckUses$.visitList(CheckUses.scala:7)
	at fpp.compiler.analysis.TopologyAnalyzer.defTopologyAnnotatedNode(TopologyAnalyzer.scala:16)
	at fpp.compiler.analysis.TopologyAnalyzer.defTopologyAnnotatedNode$(TopologyAnalyzer.scala:7)
	at fpp.compiler.analysis.CheckUses$.defTopologyAnnotatedNode(CheckUses.scala:7)
	at fpp.compiler.analysis.CheckUses$.defTopologyAnnotatedNode(CheckUses.scala:7)
	at fpp.compiler.ast.AstVisitor.matchModuleMember(AstVisitor.scala:138)
	at fpp.compiler.ast.AstVisitor.matchModuleMember$(AstVisitor.scala:4)
	at fpp.compiler.analysis.CheckUses$.matchModuleMember(CheckUses.scala:7)
	at fpp.compiler.analysis.CheckUses$.defModuleAnnotatedNode$$anonfun$1$$anonfun$1(CheckUses.scala:103)
	at fpp.compiler.util.Result$.foldLeft(Result.scala:16)
	at fpp.compiler.ast.AstStateVisitor.visitList(AstStateVisitor.scala:25)
	at fpp.compiler.ast.AstStateVisitor.visitList$(AstStateVisitor.scala:6)
	at fpp.compiler.analysis.CheckUses$.visitList(CheckUses.scala:7)
	at fpp.compiler.analysis.CheckUses$.defModuleAnnotatedNode$$anonfun$1(CheckUses.scala:103)
	at scala.util.Either.flatMap(Either.scala:352)
	at fpp.compiler.analysis.CheckUses$.defModuleAnnotatedNode(CheckUses.scala:106)
	at fpp.compiler.analysis.CheckUses$.defModuleAnnotatedNode(CheckUses.scala:88)
	at fpp.compiler.ast.AstVisitor.matchModuleMember(AstVisitor.scala:135)
	at fpp.compiler.ast.AstVisitor.matchModuleMember$(AstVisitor.scala:4)
	at fpp.compiler.analysis.CheckUses$.matchModuleMember(CheckUses.scala:7)
	at fpp.compiler.ast.AstVisitor.matchTuMember(AstVisitor.scala:155)
	at fpp.compiler.ast.AstVisitor.matchTuMember$(AstVisitor.scala:4)
	at fpp.compiler.analysis.CheckUses$.matchTuMember(CheckUses.scala:7)
	at fpp.compiler.analysis.Analyzer.transUnit$$anonfun$1(Analyzer.scala:18)
	at fpp.compiler.util.Result$.foldLeft(Result.scala:16)
	at fpp.compiler.ast.AstStateVisitor.visitList(AstStateVisitor.scala:25)
	at fpp.compiler.ast.AstStateVisitor.visitList$(AstStateVisitor.scala:6)
	at fpp.compiler.analysis.CheckUses$.visitList(CheckUses.scala:7)
	at fpp.compiler.analysis.Analyzer.transUnit(Analyzer.scala:18)
	at fpp.compiler.analysis.Analyzer.transUnit$(Analyzer.scala:6)
	at fpp.compiler.analysis.CheckUses$.transUnit(CheckUses.scala:7)
	at fpp.compiler.analysis.CheckSemantics$.tuList$$anonfun$2$$anonfun$1$$anonfun$1$$anonfun$2$$anonfun$1(CheckSemantics.scala:20)
	at fpp.compiler.util.Result$.foldLeft(Result.scala:16)
	at fpp.compiler.ast.AstStateVisitor.visitList(AstStateVisitor.scala:25)
	at fpp.compiler.ast.AstStateVisitor.visitList$(AstStateVisitor.scala:6)
	at fpp.compiler.analysis.CheckUses$.visitList(CheckUses.scala:7)
	at fpp.compiler.analysis.CheckSemantics$.tuList$$anonfun$2$$anonfun$1$$anonfun$1$$anonfun$2(CheckSemantics.scala:20)
	at scala.util.Either.flatMap(Either.scala:352)
	at fpp.compiler.analysis.CheckSemantics$.tuList$$anonfun$2$$anonfun$1$$anonfun$1(CheckSemantics.scala:35)
	at scala.util.Either.flatMap(Either.scala:352)
	at fpp.compiler.analysis.CheckSemantics$.tuList$$anonfun$2$$anonfun$1(CheckSemantics.scala:35)
	at scala.util.Either.flatMap(Either.scala:352)
	at fpp.compiler.analysis.CheckSemantics$.tuList$$anonfun$2(CheckSemantics.scala:35)
	at scala.util.Either.flatMap(Either.scala:352)
	at fpp.compiler.analysis.CheckSemantics$.tuList(CheckSemantics.scala:35)
	at fpp.compiler.tools.FPPToXml$.command$$anonfun$2$$anonfun$2$$anonfun$1$$anonfun$2(fpp-to-xml.scala:37)
	at scala.util.Either.flatMap(Either.scala:352)
	at fpp.compiler.tools.FPPToXml$.command$$anonfun$2$$anonfun$2$$anonfun$1(fpp-to-xml.scala:54)
	at scala.util.Either.flatMap(Either.scala:352)
	at fpp.compiler.tools.FPPToXml$.command$$anonfun$2$$anonfun$2(fpp-to-xml.scala:54)
	at scala.util.Either.flatMap(Either.scala:352)
	at fpp.compiler.tools.FPPToXml$.command$$anonfun$2(fpp-to-xml.scala:54)
	at scala.util.Either.flatMap(Either.scala:352)
	at fpp.compiler.tools.FPPToXml$.command(fpp-to-xml.scala:54)
	at fpp.compiler.tools.FPPToXml$.main$$anonfun$1(fpp-to-xml.scala:67)
	at fpp.compiler.util.Tool.mainMethod(Tool.scala:20)
	at fpp.compiler.tools.FPPToXml$.main(fpp-to-xml.scala:67)
	at fpp.compiler.tools.FPPToXml.main(fpp-to-xml.scala)
```

**Comment by LeStarch** [comment]
Correction: this error occurs even when the topology exists as long as the topology is referred to with the module name within the existing module. 

```
module Ref {
    topology Ref {
        import Ref.Abc # Errors regardless if Ref.Abc exists or not, but when the module "Ref" matches the containing module
    }
}
